
export let DatosJson = [
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2024-04-03",
    "tipo_documento": "E",
    "numero_documento": "661093295",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Denise",
    "apellido": "Singh",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Kevin Fisher"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-02-15",
    "tipo_documento": "T",
    "numero_documento": "931271948",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Courtney",
    "apellido": "Jones",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Christopher Gibson"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-06-27",
    "tipo_documento": "T",
    "numero_documento": "729929820",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Ashley",
    "apellido": "Fox",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Brian Blair"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-04-05",
    "tipo_documento": "R",
    "numero_documento": "502487293",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Christopher",
    "apellido": "Lopez",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Taylor Jenkins"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-04-16",
    "tipo_documento": "C",
    "numero_documento": "119233256",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Gina",
    "apellido": "Brown",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Rodney Russell DDS"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-01-02",
    "tipo_documento": "C",
    "numero_documento": "575973458",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "David",
    "apellido": "Wilson",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Joe Nash"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-05-14",
    "tipo_documento": "R",
    "numero_documento": "560699434",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Brian",
    "apellido": "Baker",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Nicole Smith"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-10-10",
    "tipo_documento": "C",
    "numero_documento": "823441982",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Charles",
    "apellido": "Steele",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Victoria Bush"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-11-10",
    "tipo_documento": "T",
    "numero_documento": "923015978",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Adam",
    "apellido": "Pratt",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Ronnie Baker"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-05-28",
    "tipo_documento": "R",
    "numero_documento": "397671596",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Danielle",
    "apellido": "Williams",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Donald Bridges"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-11-13",
    "tipo_documento": "E",
    "numero_documento": "135763338",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Michael",
    "apellido": "Lopez",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Patricia Olson"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-12-11",
    "tipo_documento": "C",
    "numero_documento": "217974690",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Kyle",
    "apellido": "Warner",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Sharon Compton"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-12-08",
    "tipo_documento": "C",
    "numero_documento": "586183077",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Jason",
    "apellido": "Casey",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Mary Bullock"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2023-01-17",
    "tipo_documento": "E",
    "numero_documento": "659991870",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Tammie",
    "apellido": "Garza",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Charles Mitchell"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-02-19",
    "tipo_documento": "R",
    "numero_documento": "948754192",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Joshua",
    "apellido": "Robertson",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Katherine Moore"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-05-18",
    "tipo_documento": "R",
    "numero_documento": "277945112",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Eric",
    "apellido": "Gray",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Christine Green"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2021-05-25",
    "tipo_documento": "E",
    "numero_documento": "871150057",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Rachel",
    "apellido": "Williams",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Margaret Wallace"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-12-29",
    "tipo_documento": "T",
    "numero_documento": "232643146",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "William",
    "apellido": "Schaefer",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Wendy Chambers"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2023-06-23",
    "tipo_documento": "R",
    "numero_documento": "863278661",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Adam",
    "apellido": "Braun",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Katherine Riley"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-08-04",
    "tipo_documento": "R",
    "numero_documento": "683436131",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Bobby",
    "apellido": "Davis",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "John Allen"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-11-18",
    "tipo_documento": "C",
    "numero_documento": "116483332",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Christian",
    "apellido": "Howard",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Michael Lawrence"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-06-15",
    "tipo_documento": "R",
    "numero_documento": "705127093",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Misty",
    "apellido": "Taylor",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Benjamin Johnson"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-09-10",
    "tipo_documento": "C",
    "numero_documento": "161386540",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Jessica",
    "apellido": "Kim",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Tanner Baker"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-01-12",
    "tipo_documento": "C",
    "numero_documento": "658804472",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Philip",
    "apellido": "Berger",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Megan Young"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-09-14",
    "tipo_documento": "C",
    "numero_documento": "618737701",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Deborah",
    "apellido": "Gibson",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Maria Guerrero"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-09-13",
    "tipo_documento": "E",
    "numero_documento": "120787148",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Leah",
    "apellido": "Cook",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Kaitlyn Mendez"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-10-27",
    "tipo_documento": "E",
    "numero_documento": "359127911",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Cynthia",
    "apellido": "Roberts",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Matthew Williams"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-07-25",
    "tipo_documento": "C",
    "numero_documento": "545977244",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Kristi",
    "apellido": "Bradley",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Sandra Ray"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-06-08",
    "tipo_documento": "R",
    "numero_documento": "238297774",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Anna",
    "apellido": "Wade",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Jill Ford"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-01-13",
    "tipo_documento": "C",
    "numero_documento": "763651289",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Dawn",
    "apellido": "Horne",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Laura Olsen"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-08-09",
    "tipo_documento": "C",
    "numero_documento": "376275011",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Tracy",
    "apellido": "Carr",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Michelle Sutton"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-09-16",
    "tipo_documento": "R",
    "numero_documento": "729003796",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Jaime",
    "apellido": "Fuentes",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Scott Dickerson"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-05-30",
    "tipo_documento": "C",
    "numero_documento": "292355305",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Sarah",
    "apellido": "Allen",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Russell Lopez"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-04-26",
    "tipo_documento": "T",
    "numero_documento": "221089886",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Jacob",
    "apellido": "Martin",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Carrie Hughes"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-01-02",
    "tipo_documento": "E",
    "numero_documento": "680039459",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Robert",
    "apellido": "Thomas",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Alicia West"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-05-17",
    "tipo_documento": "E",
    "numero_documento": "164592359",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Jason",
    "apellido": "Rocha",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Jason Mosley"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-10-25",
    "tipo_documento": "R",
    "numero_documento": "158523221",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Scott",
    "apellido": "Barton",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Brian Williams"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-11-17",
    "tipo_documento": "T",
    "numero_documento": "698100029",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Rachel",
    "apellido": "Powell",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Clinton Keller"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-06-11",
    "tipo_documento": "E",
    "numero_documento": "308184999",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Rebecca",
    "apellido": "Watson",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Taylor Cooper"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2021-09-03",
    "tipo_documento": "R",
    "numero_documento": "61756882",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Jennifer",
    "apellido": "Lopez",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Clinton Sharp"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2024-01-23",
    "tipo_documento": "T",
    "numero_documento": "907551393",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Joy",
    "apellido": "Barr",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Jill Richardson"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2023-05-23",
    "tipo_documento": "C",
    "numero_documento": "994836661",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Kayla",
    "apellido": "Wiley",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Kevin Khan"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2020-08-25",
    "tipo_documento": "T",
    "numero_documento": "703324960",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Robert",
    "apellido": "Hale",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "David Jones"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-12-06",
    "tipo_documento": "E",
    "numero_documento": "414885818",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Samantha",
    "apellido": "Morrow",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Gina Robertson"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2021-02-21",
    "tipo_documento": "C",
    "numero_documento": "21635965",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Meredith",
    "apellido": "Poole",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Taylor Matthews"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-08-17",
    "tipo_documento": "E",
    "numero_documento": "598727551",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Robert",
    "apellido": "Cherry",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "John Aguilar"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-11-16",
    "tipo_documento": "T",
    "numero_documento": "915516397",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Jacqueline",
    "apellido": "Aguirre",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Katherine Sexton"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-11-10",
    "tipo_documento": "R",
    "numero_documento": "159834394",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "William",
    "apellido": "Zamora",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Patricia Mann"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-08-12",
    "tipo_documento": "R",
    "numero_documento": "549063293",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Samantha",
    "apellido": "Griffith",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Kevin Wilson"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2021-10-06",
    "tipo_documento": "R",
    "numero_documento": "303065221",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "James",
    "apellido": "Wright",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Eric Perez"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-10-23",
    "tipo_documento": "T",
    "numero_documento": "4956136",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Michael",
    "apellido": "Hall",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "William Scott"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-04-25",
    "tipo_documento": "T",
    "numero_documento": "710858491",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Victor",
    "apellido": "Roberts",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Tammy Hill"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2024-03-08",
    "tipo_documento": "R",
    "numero_documento": "149656904",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Joshua",
    "apellido": "King",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Mike Thomas"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-02-06",
    "tipo_documento": "E",
    "numero_documento": "958415440",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Justin",
    "apellido": "Shaffer",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Debra Friedman"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2021-05-07",
    "tipo_documento": "E",
    "numero_documento": "569344100",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Sonya",
    "apellido": "Brady",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Nicole West"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2021-04-14",
    "tipo_documento": "C",
    "numero_documento": "518970745",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "David",
    "apellido": "Davis",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Christopher Mueller"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2021-10-28",
    "tipo_documento": "T",
    "numero_documento": "865014428",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Christina",
    "apellido": "Knapp",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Ricardo Hicks"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-06-12",
    "tipo_documento": "E",
    "numero_documento": "390381773",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Kelsey",
    "apellido": "Jimenez",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Janet Miller"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2024-02-02",
    "tipo_documento": "T",
    "numero_documento": "141195433",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Brian",
    "apellido": "Downs",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Mrs. Donna Fletcher"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2020-12-18",
    "tipo_documento": "R",
    "numero_documento": "969805012",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Michael",
    "apellido": "Klein",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Adam Hicks"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-06-25",
    "tipo_documento": "R",
    "numero_documento": "949649831",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Katelyn",
    "apellido": "Benton",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Daniel Brown"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-01-06",
    "tipo_documento": "T",
    "numero_documento": "78200809",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Karla",
    "apellido": "Mendoza",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Wanda Patton"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-01-31",
    "tipo_documento": "C",
    "numero_documento": "724946672",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Jeremy",
    "apellido": "Chandler",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Justin Castillo"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-10-16",
    "tipo_documento": "E",
    "numero_documento": "59400957",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Jessica",
    "apellido": "Boyer",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Heather Morris"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-06-28",
    "tipo_documento": "C",
    "numero_documento": "540943018",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Samantha",
    "apellido": "Smith",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Ashley Eaton"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2021-05-16",
    "tipo_documento": "R",
    "numero_documento": "615479865",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Brad",
    "apellido": "Massey",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Kathryn Pope"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2021-10-30",
    "tipo_documento": "C",
    "numero_documento": "447295433",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Jaime",
    "apellido": "Harris",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Nicole Ferrell"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-09-24",
    "tipo_documento": "C",
    "numero_documento": "35810829",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Brian",
    "apellido": "Barrett",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Erika Anderson"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-05-22",
    "tipo_documento": "T",
    "numero_documento": "969861512",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Paul",
    "apellido": "Herring",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Melvin Cantrell"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-11-27",
    "tipo_documento": "T",
    "numero_documento": "118583302",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Joanna",
    "apellido": "Wilson",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Jessica Carpenter"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2022-09-10",
    "tipo_documento": "R",
    "numero_documento": "820626335",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Christopher",
    "apellido": "Brown",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Martin Nguyen"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2022-04-04",
    "tipo_documento": "T",
    "numero_documento": "529435866",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Melissa",
    "apellido": "Ortiz",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Bryan Sullivan"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-06-26",
    "tipo_documento": "C",
    "numero_documento": "312503777",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Eduardo",
    "apellido": "Evans",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Michelle Orr"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2020-05-05",
    "tipo_documento": "E",
    "numero_documento": "923477618",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Amanda",
    "apellido": "Smith",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Kyle Garrett"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-10-19",
    "tipo_documento": "T",
    "numero_documento": "808633346",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Kristie",
    "apellido": "Marquez",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Sonia Moon"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2023-12-04",
    "tipo_documento": "C",
    "numero_documento": "944551755",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Anna",
    "apellido": "Alvarez",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Kayla Norris"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-08-14",
    "tipo_documento": "T",
    "numero_documento": "473942282",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Ann",
    "apellido": "Velasquez",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Debra Schroeder"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-08-13",
    "tipo_documento": "T",
    "numero_documento": "80253398",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Jamie",
    "apellido": "Williams",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Richard Suarez"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-03-28",
    "tipo_documento": "E",
    "numero_documento": "53649272",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Ryan",
    "apellido": "Molina",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Stephanie Green"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2024-02-17",
    "tipo_documento": "E",
    "numero_documento": "799501786",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Brandi",
    "apellido": "Watson",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Troy Suarez"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2024-02-16",
    "tipo_documento": "R",
    "numero_documento": "682042568",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "David",
    "apellido": "Castaneda",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Patricia Martinez"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2020-04-02",
    "tipo_documento": "T",
    "numero_documento": "201568552",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Darren",
    "apellido": "Smith",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Roy Cruz IV"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-08-23",
    "tipo_documento": "E",
    "numero_documento": "447588427",
    "tipo_plan": "PBS",
    "sede": "Industriales",
    "nombre": "Stacy",
    "apellido": "Robinson",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Mark Gibson"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2021-09-25",
    "tipo_documento": "R",
    "numero_documento": "610922081",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "Monica",
    "apellido": "Morgan",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Vanessa Craig"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2021-04-28",
    "tipo_documento": "C",
    "numero_documento": "15884084",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Yesenia",
    "apellido": "Brown",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Michelle Kirby"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-08-14",
    "tipo_documento": "R",
    "numero_documento": "276986365",
    "tipo_plan": "PBS",
    "sede": "Calle 100",
    "nombre": "Tommy",
    "apellido": "Wallace",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Danielle Martinez"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2021-03-22",
    "tipo_documento": "T",
    "numero_documento": "206766072",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "James",
    "apellido": "Kelley",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A012 - FIEBRE PARATIFOIDEA B",
    "medico_remitente": "Stephanie Moody"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2021-07-30",
    "tipo_documento": "T",
    "numero_documento": "872337067",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "James",
    "apellido": "Hall",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Michael Johnson"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-01-19",
    "tipo_documento": "C",
    "numero_documento": "98082811",
    "tipo_plan": "Particular",
    "sede": "Chipichape",
    "nombre": "Debbie",
    "apellido": "Quinn",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A011 - FIEBRE PARATIFOIDEA A",
    "medico_remitente": "Sharon Gonzalez"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2021-12-27",
    "tipo_documento": "C",
    "numero_documento": "425714392",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Janet",
    "apellido": "Lee",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Adam Hill"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-02-07",
    "tipo_documento": "E",
    "numero_documento": "721800665",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Philip",
    "apellido": "Ward",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A001 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO EL TOR",
    "medico_remitente": "Jasmine Haas"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-12-04",
    "tipo_documento": "R",
    "numero_documento": "5649345",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Elizabeth",
    "apellido": "Chambers",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Jeremy Howe"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2023-12-29",
    "tipo_documento": "T",
    "numero_documento": "57595716",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Alicia",
    "apellido": "Young",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Jesus Mahoney"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2022-12-11",
    "tipo_documento": "E",
    "numero_documento": "934189195",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Peter",
    "apellido": "Hernandez",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Jose Martin"
  },
  {
    "Usuario_Gestor": "claulelo",
    "fecha_gestion": "2023-12-27",
    "tipo_documento": "T",
    "numero_documento": "659129703",
    "tipo_plan": "Poliza",
    "sede": "Industriales",
    "nombre": "Lindsay",
    "apellido": "Green",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "0 - NO APLICA",
    "medico_remitente": "Veronica Moran"
  },
  {
    "Usuario_Gestor": "adrijaag",
    "fecha_gestion": "2020-05-15",
    "tipo_documento": "T",
    "numero_documento": "843053488",
    "tipo_plan": "Poliza",
    "sede": "Calle 100",
    "nombre": "Monica",
    "apellido": "Sullivan",
    "tipo_gestion": "Evaluacion Hidroterapia",
    "diagnostico": "A000 - COLERA DEBIDO A VIBRIO CHOLERAE O1 BIOTIPO CHOLERAE",
    "medico_remitente": "Tammy Hill"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2020-01-09",
    "tipo_documento": "R",
    "numero_documento": "983385490",
    "tipo_plan": "Particular",
    "sede": "Calle 100",
    "nombre": "Jessica",
    "apellido": "Smith",
    "tipo_gestion": "Acondicionamiento Fisco",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Edward Carrillo"
  },
  {
    "Usuario_Gestor": "andrgohr",
    "fecha_gestion": "2023-07-29",
    "tipo_documento": "T",
    "numero_documento": "784369913",
    "tipo_plan": "Poliza",
    "sede": "Chipichape",
    "nombre": "Scott",
    "apellido": "Maldonado",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A009 - COLERA NO ESPECIFICADO",
    "medico_remitente": "Heather Smith"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-09-19",
    "tipo_documento": "E",
    "numero_documento": "378229929",
    "tipo_plan": "Particular",
    "sede": "Industriales",
    "nombre": "James",
    "apellido": "Gutierrez",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A010 - FIEBRE TIFOIDEA",
    "medico_remitente": "Daniel Burch"
  },
  {
    "Usuario_Gestor": "pedrper",
    "fecha_gestion": "2023-02-25",
    "tipo_documento": "C",
    "numero_documento": "947022585",
    "tipo_plan": "PBS",
    "sede": "Chipichape",
    "nombre": "Charlotte",
    "apellido": "Dyer",
    "tipo_gestion": "Evaluacion miembro superior",
    "diagnostico": "A013 - FIEBRE PARATIFOIDEA C",
    "medico_remitente": "Erica Martinez"
  }
]